language: node_js

node_js:
  - lts/carbon
  - lts/dubnium

jobs:
  include:
    - stage: test
      name: 'Unit Tests'
      script: yarn test
    - stage: build
      name: 'Compile to JavaScript'
      script: yarn build
    - stage: docs
      name: 'Build Docs'
      script: yarn styleguide:build
    - &deploy_npm
      stage: deploy_npm
      name: 'Deploy to npmjs.org'
      script: echo "[DRY_RUN] Deploying to npmjs.org..."
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_token: $NPM_API_TOKEN
        src: ./dist/
        edge: true
        dry_run: true
        on:
          branch: master
    - <<: *deploy_npm
      script: echo "Deploying to npmjs.org..."
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_token: $NPM_API_TOKEN
        src: ./dist/
        edge: true
        on:
          tags: true
    - stage: deploy_surge
      name: 'Deploy to surge.sh'
      script: echo "Deploying to surge.sh..."
      deploy:
        provider: surge
        login: $SURGE_LOGIN
        token: $SURGE_TOKEN
        project: ./styleguide/
        domain: $SURGE_DOMAIN
        edge: true
        on:
          tags: true
