language: node_js

node_js:
  - lts/dubnium

jobs:
  include:
    - stage: test
      name: 'Unit Tests'
      script: yarn test
    - stage: build
      name: 'Compile & deploy to npm.js'
      script: yarn build
      deploy:
        - provider: npm
          email: $NPM_EMAIL
          api_token: $NPM_API_TOKEN
          src: ./dist/
          edge: true
          dry_run: true
          on:
            branch: master
        - provider: npm
          email: $NPM_EMAIL
          api_token: $NPM_API_TOKEN
          src: ./dist/
          edge: true
          on:
            tags: true
    - stage: docs
      name: 'Build Docs & deploy to surge.sh'
      script: yarn styleguide:build
      deploy:
        provider: surge
        login: $SURGE_LOGIN
        token: $SURGE_TOKEN
        project: ./styleguide/
        domain: $SURGE_DOMAIN
        edge: true
        on:
          tags: true
